# Generated by Django 2.0.6 on 2019-09-23 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userData',
        ),
    ]
