# Generated by Django 2.0.6 on 2019-09-23 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('firstapp', '0002_delete_userdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='userData',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(default='', max_length=200)),
                ('userPassword', models.BigIntegerField()),
                ('userEmail', models.CharField(default='', max_length=200)),
                ('userImage', models.CharField(default='', max_length=200)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
    ]
