# Generated by Django 2.0.6 on 2019-09-25 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_userdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='userPassword',
            field=models.CharField(default='', max_length=200),
        ),
    ]
